### ISSUE TITLE
How can I use beautify in Ace Editor?

### ISSUE THREAD

**Issue by zhil** [norberttech/aceeditor-bundle#31]
How can I add extensions, like

```
var beautiful = ace.require("ace/ext/beautify");
beautiful.beautify();
```

@norzechowicz I would appreciate any suggestions :)

**Comment by norzechowicz** [comment]
Hey @zhil I don't see any clean way to extend ace editor behavior this way except overriding the https://github.com/norzechowicz/aceeditor-bundle/blob/master/Resources/views/Form/div_layout.html.twig file and then overriding also `norzechowicz_ace_editor.form.resource` parameter https://github.com/norzechowicz/aceeditor-bundle/blob/master/Resources/config/form.xml 
Let me know if that works!

**Comment by zhil** [comment]
@norzechowicz thanks for suggestion! Let me try to create PR with that changes?

**Comment by norzechowicz** [comment]
Yeah go ahead, just please try to make it optional so if someone does not want to use `ace.require` this bundle will not try to force him
